default_settings:
    trainer_type: ppo
    checkpoint_interval: 500000
    threaded: false
    max_steps: 5.0e5
    time_horizon: 64
    summary_freq: 10000
    hyperparameters:
        batch_size: 1024
        buffer_size: 10240
        learning_rate: 3.0e-4
        learning_rate_schedule: linear
        beta: 5.0e-3
        epsilon: 0.2
        lambd: 0.95
        num_epoch: 3
    network_settings:
        hidden_units: 128
        num_layers: 2
        normalize: false
        vis_encode_type: simple
        memory:
            memory_size: 128
            sequence_length: 64
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
behaviors:
    Hummingbird:
        time_horizon: 128
        max_steps: 5.0e6
        hyperparameters:
            batch_size: 2048
            buffer_size: 20480
        network_settings:
            hidden_units: 512
            num_layers: 3